[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools-scm",
]

[tool.setuptools]
packages = ["goat_storytelling_agent"]

[project]
name = "goat_storytelling_agent"
version = "0.0.1"
dependencies = [
    "requests==2.31.0",
    "transformers==4.36.0"
]